const cars = [
  {
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2023,
    purchasePrice: 450000,
    rentingPrice: 1500,
    engineType: "V12",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 563,
    appreciationValue: 5,
    mainImage: "/images/rolls_royce_phantom.jpg",
    additionalImages: [
      "/images/rolls_royce_phantom_2.jpg",
      "/images/rolls_royce_phantom_3.jpg",
      "/images/rolls_royce_phantom_4.jpg",
    ],
  },
  {
    make: "Bentley",
    model: "Continental GT",
    year: 2023,
    purchasePrice: 220000,
    rentingPrice: 1000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 542,
    appreciationValue: 4,
    mainImage: "/images/bentley_continental_gt.jpg",
    additionalImages: [
      "/images/bentley_continental_gt_2.jpg",
      "/images/bentley_continental_gt_3.jpg",
      "/images/bentley_continental_gt_4.jpg",
    ],
  },
  {
    make: "Lamborghini",
    model: "Aventador",
    year: 2023,
    purchasePrice: 500000,
    rentingPrice: 2500,
    engineType: "V12",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 730,
    appreciationValue: 6,
    mainImage: "/images/lamborghini_aventador.jpg",
    additionalImages: [
      "/images/lamborghini_aventador_2.jpg",
      "/images/lamborghini_aventador_3.jpg",
      "/images/lamborghini_aventador_4.jpg",
    ],
  },
  {
    make: "Ferrari",
    model: "488 Pista",
    year: 2023,
    purchasePrice: 330000,
    rentingPrice: 2000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 710,
    appreciationValue: 7,
    mainImage: "/images/ferrari_488_pista.jpg",
    additionalImages: [
      "/images/ferrari_488_pista_2.jpg",
      "/images/ferrari_488_pista_3.jpg",
      "/images/ferrari_488_pista_4.jpg",
    ],
  },
  {
    make: "Aston Martin",
    model: "DB11",
    year: 2023,
    purchasePrice: 220000,
    rentingPrice: 1000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 503,
    appreciationValue: 4,
    mainImage: "/images/aston_martin_db11.jpg",
    additionalImages: [
      "/images/aston_martin_db11_2.jpg",
      "/images/aston_martin_db11_3.jpg",
      "/images/aston_martin_db11_4.jpg",
    ],
  },
  {
    make: "Porsche",
    model: "911 Turbo S",
    year: 2023,
    purchasePrice: 230000,
    rentingPrice: 800,
    engineType: "Flat-6",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 640,
    appreciationValue: 3,
    mainImage: "/images/porsche_911_turbo_s.jpg",
    additionalImages: [
      "/images/porsche_911_turbo_s_2.jpg",
      "/images/porsche_911_turbo_s_3.jpg",
      "/images/porsche_911_turbo_s_4.jpg",
    ],
  },
  {
    make: "Mercedes-Benz",
    model: "S-Class",
    year: 2023,
    purchasePrice: 120000,
    rentingPrice: 500,
    engineType: "I6",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 429,
    appreciationValue: 2,
    mainImage: "/images/mercedes_benz_s_class.jpg",
    additionalImages: [
      "/images/mercedes_benz_s_class_2.jpg",
      "/images/mercedes_benz_s_class_3.jpg",
      "/images/mercedes_benz_s_class_4.jpg",
    ],
  },
  {
    make: "BMW",
    model: "7 Series",
    year: 2023,
    purchasePrice: 100000,
    rentingPrice: 400,
    engineType: "I6",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 335,
    appreciationValue: 2,
    mainImage: "/images/bmw_7_series.jpg",
    additionalImages: [
      "/images/bmw_7_series_2.jpg",
      "/images/bmw_7_series_3.jpg",
      "/images/bmw_7_series_4.jpg",
    ],
  },
  {
    make: "Audi",
    model: "R8",
    year: 2023,
    purchasePrice: 200000,
    rentingPrice: 1000,
    engineType: "V10",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 562,
    appreciationValue: 5,
    mainImage: "/images/audi_r8.jpg",
    additionalImages: [
      "/images/audi_r8_2.jpg",
      "/images/audi_r8_3.jpg",
      "/images/audi_r8_4.jpg",
    ],
  },
  {
    make: "Tesla",
    model: "Model S Plaid",
    year: 2023,
    purchasePrice: 135000,
    rentingPrice: 500,
    engineType: "Electric",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 1020,
    appreciationValue: 4,
    mainImage: "/images/tesla_model_s_plaid.jpg",
    additionalImages: [
      "/images/tesla_model_s_plaid_2.jpg",
      "/images/tesla_model_s_plaid_3.jpg",
      "/images/tesla_model_s_plaid_4.jpg",
    ],
  },
  {
    make: "Range Rover",
    model: "Autobiography",
    year: 2023,
    purchasePrice: 150000,
    rentingPrice: 600,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 557,
    appreciationValue: 3,
    mainImage: "/images/range_rover_autobiography.jpg",
    additionalImages: [
      "/images/range_rover_autobiography_2.jpg",
      "/images/range_rover_autobiography_3.jpg",
      "/images/range_rover_autobiography_4.jpg",
    ],
  },
  {
    make: "Maserati",
    model: "Ghibli",
    year: 2023,
    purchasePrice: 85000,
    rentingPrice: 400,
    engineType: "V6",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 345,
    appreciationValue: 2,
    mainImage: "/images/maserati_ghibli.jpg",
    additionalImages: [
      "/images/maserati_ghibli_2.jpg",
      "/images/maserati_ghibli_3.jpg",
      "/images/maserati_ghibli_4.jpg",
    ],
  },
  {
    make: "McLaren",
    model: "720S",
    year: 2023,
    purchasePrice: 300000,
    rentingPrice: 2000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 710,
    appreciationValue: 6,
    mainImage: "/images/mclaren_720s.jpg",
    additionalImages: [
      "/images/mclaren_720s_2.jpg",
      "/images/mclaren_720s_3.jpg",
      "/images/mclaren_720s_4.jpg",
    ],
  },
  {
    make: "Jaguar",
    model: "F-Type",
    year: 2023,
    purchasePrice: 80000,
    rentingPrice: 400,
    engineType: "V6",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 296,
    appreciationValue: 3,
    mainImage: "/images/jaguar_f_type.jpg",
    additionalImages: [
      "/images/jaguar_f_type_2.jpg",
      "/images/jaguar_f_type_3.jpg",
      "/images/jaguar_f_type_4.jpg",
    ],
  },
  {
    make: "Bentley",
    model: "Bentayga",
    year: 2023,
    purchasePrice: 200000,
    rentingPrice: 1000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 542,
    appreciationValue: 4,
    mainImage: "/images/bentley_bentayga.jpg",
    additionalImages: [
      "/images/bentley_bentayga_2.jpg",
      "/images/bentley_bentayga_3.jpg",
      "/images/bentley_bentayga_4.jpg",
    ],
  },
  {
    make: "Lamborghini",
    model: "Urus",
    year: 2023,
    purchasePrice: 225000,
    rentingPrice: 1200,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 641,
    appreciationValue: 6,
    mainImage: "/images/lamborghini_urus.jpg",
    additionalImages: [
      "/images/lamborghini_urus_2.jpg",
      "/images/lamborghini_urus_3.jpg",
      "/images/lamborghini_urus_4.jpg",
    ],
  },
  {
    make: "Ferrari",
    model: "Portofino",
    year: 2023,
    purchasePrice: 230000,
    rentingPrice: 1500,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 591,
    appreciationValue: 5,
    mainImage: "/images/ferrari_portofino.jpg",
    additionalImages: [
      "/images/ferrari_portofino_2.jpg",
      "/images/ferrari_portofino_3.jpg",
      "/images/ferrari_portofino_4.jpg",
    ],
  },
  {
    make: "Porsche",
    model: "Panamera",
    year: 2023,
    purchasePrice: 100000,
    rentingPrice: 500,
    engineType: "V6",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 330,
    appreciationValue: 2,
    mainImage: "/images/porsche_panamera.jpg",
    additionalImages: [
      "/images/porsche_panamera_2.jpg",
      "/images/porsche_panamera_3.jpg",
      "/images/porsche_panamera_4.jpg",
    ],
  },
  {
    make: "Rolls-Royce",
    model: "Ghost",
    year: 2023,
    purchasePrice: 350000,
    rentingPrice: 1500,
    engineType: "V12",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 563,
    appreciationValue: 5,
    mainImage: "/images/rolls_royce_ghost.jpg",
    additionalImages: [
      "/images/rolls_royce_ghost_2.jpg",
      "/images/rolls_royce_ghost_3.jpg",
      "/images/rolls_royce_ghost_4.jpg",
    ],
  },
  {
    make: "Cadillac",
    model: "Escalade",
    year: 2023,
    purchasePrice: 80000,
    rentingPrice: 300,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 420,
    appreciationValue: 2,
    mainImage: "/images/cadillac_escalade.jpg",
    additionalImages: [
      "/images/cadillac_escalade_2.jpg",
      "/images/cadillac_escalade_3.jpg",
      "/images/cadillac_escalade_4.jpg",
    ],
  },
];

export default cars;
