const cars = [
  {
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2023,
    purchasePrice: 450000,
    rentingPrice: 1500,
    engineType: "V12",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 563,
    appreciationValue: 5,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729870411/download_2_fopoxf.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729870413/download_1_hjjxpg.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729870411/Rolls_Royce_Phantom_zvnwld.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729870409/2017_Rolls-Royce_Phantom_Interior_by_Levon_xhzvwm.jpg",
    ],
    description: [
      "The Rolls-Royce Phantom 2023 is the epitome of luxury and sophistication, blending unparalleled craftsmanship with cutting-edge technology. Every detail of this iconic vehicle, from its handcrafted interior to its powerful V12 engine, has been meticulously designed to offer an unmatched driving experience.",
      "Inside, the Phantom is adorned with luxurious materials, customizable options, and advanced technology that makes every journey an indulgence. This model continues to stand as a benchmark in the automotive world, a true symbol of prestige and power.",
    ],
  },
  {
    make: "Bentley",
    model: "Continental GT",
    year: 2023,
    purchasePrice: 220000,
    rentingPrice: 1000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 542,
    appreciationValue: 4,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729876326/download_2_jctmbk.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729876328/download_1_dojb9d.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729876328/Bentley_looks_towards_an_electrified_grand_touring_future_with_its_twin_release_tvjlus.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729876332/2025_Bentley_Continental_GT__A_Blend_of_Luxury_and_Performance___Bentley_Continental_GT_Review_mpkqfi.jpg",
    ],
    description: [
      "The 2023 Bentley Continental GT exemplifies refined power and elegance, seamlessly merging British craftsmanship with contemporary design. Under its hood, the potent V8 engine provides exhilarating performance, while the sophisticated all-wheel drive ensures unparalleled handling.",
      "The interior of the Continental GT is a masterpiece of opulence, featuring hand-stitched leather, polished wood veneers, and customizable options that cater to each driver’s preferences. Bentley’s engineering excellence shines through, offering a grand touring experience unlike any other.",
    ],
  },
  {
    make: "Lamborghini",
    model: "Aventador",
    year: 2023,
    purchasePrice: 500000,
    rentingPrice: 2500,
    engineType: "V12",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 730,
    appreciationValue: 6,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729945584/Lamborghini_Aventador_S_Wheels_Vehicle_Gallery_zrvx0r.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729945583/download_2_pzulgx.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729945583/download_1_cavbhm.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729945583/Interior_of_the_Lamborghini_Aventador_Super_Veloce_Jota_Roadster_painted_in_Grigio_Titans_Photo_taken_by__jeremy_lhj_on_Instagram_zkbvof.jpg",
    ],
    description: [
      "The Lamborghini Aventador 2023 redefines performance with its aggressive styling and roaring V12 engine, delivering a top-tier supercar experience. The Aventador is built for speed, with a finely tuned all-wheel-drive system that makes it as agile as it is powerful.",
      "Step inside, and you’re greeted by an interior that combines luxury with a race-inspired feel, featuring state-of-the-art technology and premium finishes. From its aerodynamic design to its unmatched power output, the Aventador remains a testament to Lamborghini’s legacy in the supercar world.",
    ],
  },
  {
    make: "Ferrari",
    model: "488 Pista",
    year: 2023,
    purchasePrice: 330000,
    rentingPrice: 2000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 710,
    appreciationValue: 7,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946034/Ferrari_488_pista_1_bbmqbb.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946034/Interior_of_the_Ferrari_488_Pista_painted_in_the_tailor_made_color_Bianco_Liana_w__central_stripes_painted_in_Rosso_Coburn_Photo_posted_by__ferraritailormade_on_Instagram_lmrp7k.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946034/Ferrari_488_Pista_doc0qv.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946034/Ferrari_488_Pista_-_L_ART_DE_L_AUTOMOBILE_-_France_ud9ksr.jpg",
    ],
    description: [
      "The Ferrari 488 Pista 2023 is an embodiment of raw power and dynamic performance, taking the iconic Ferrari design language to new heights. Its turbocharged V8 engine offers breathtaking acceleration and responsiveness, ensuring that every drive is exhilarating.",
      "With aerodynamic enhancements and lightweight materials, the 488 Pista is engineered for speed and precision. Inside, the driver-focused cockpit features premium materials and cutting-edge technology, making it a true masterpiece for any driving enthusiast.",
    ],
  },
  {
    make: "Aston Martin",
    model: "DB11",
    year: 2023,
    purchasePrice: 220000,
    rentingPrice: 1000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 503,
    appreciationValue: 4,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946599/Midnight_Blue_Aston_Martin__Urban_Elegance_in_Motion_cblfjp.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946599/download_1_hzab6h.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946599/ASTON_MARTIN_DB11_INTERIOR_SEATS_lqpmdt.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729946599/Aston_Martin_D11_yqdugm.jpg",
    ],
    description: [
      "The Aston Martin DB11 2023 is a stunning blend of elegance and performance, showcasing the brand’s commitment to craftsmanship and innovation. Its powerful V8 engine delivers exhilarating performance while maintaining a level of sophistication that is unmistakably Aston Martin.",
      "The interior offers a luxurious sanctuary, featuring premium leather, advanced technology, and ample customization options. With its striking design and unparalleled driving experience, the DB11 continues to be a standout in the luxury sports car segment.",
    ],
  },
  {
    make: "Mercedes-Benz",
    model: "SClass",
    year: 2023,
    purchasePrice: 120000,
    rentingPrice: 800,
    engineType: "I6",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 429,
    appreciationValue: 2,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729949280/Mercedes_E63_AMG_distht.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729949280/Mercedes-Benz_S-Class_W223_2021_gtjs1v.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729949281/download_1_aqnhcv.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729949281/Mercedes_k8yrlv.jpg",
    ],
    description: [
      "The 2023 Mercedes-Benz S-Class is the pinnacle of luxury sedans, featuring state-of-the-art technology and unparalleled comfort. With a powerful inline-six engine, the S-Class offers smooth acceleration and an incredibly refined ride.",
      "Inside, it boasts an opulent cabin equipped with the latest infotainment systems, premium materials, and advanced safety features. The S-Class sets a new standard for what a luxury sedan should be, ensuring every drive is a memorable experience.",
    ],
  },
  {
    make: "BMW",
    model: "7 Series",
    year: 2023,
    purchasePrice: 100000,
    rentingPrice: 400,
    engineType: "I6",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 335,
    appreciationValue: 2,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948838/Nuova_BMW_Serie_7_mpmwoq.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948838/Could_the_BMW_7_Series_be_your_next_work_space____IndesignLive_zggsna.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948837/bmw_7_series_2023_nkqxva.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948836/BMW_8_Series_can_over-the-air_update_from_your_smartphone_zi5ee0.jpg",
    ],
    description: [
      "The 2023 BMW 7 Series redefines luxury with its cutting-edge design and innovative technology. Its inline-six engine delivers a harmonious balance of power and efficiency, making it a top choice for discerning drivers.",
      "The interior is meticulously crafted, offering a blend of comfort and advanced features. With spacious seating and a host of connectivity options, the 7 Series ensures that every journey is as enjoyable as it is luxurious.",
    ],
  },
  {
    make: "Tesla",
    model: "Model S",
    year: 2023,
    purchasePrice: 120000,
    rentingPrice: 450,
    engineType: "Electric",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 1020,
    appreciationValue: 3,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948163/New_Top_30_Tesla_Model_S_Cars_2025_b0wzxp.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948163/This_is_the_new_interior_of_Tesla_s_Model_S_and_Model_X___TechCrunch_rvxiuf.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948163/Tesla_Model_S_Premium_Electric_Car_Editorial_Photo_-_Image_of_vehicles_luxury__65998516_kzh7in.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729948164/New_Tesla_Model_S_refresh_2021_gduyqh.jpg",
    ],
    description: [
      "The 2023 Tesla Model S represents the forefront of electric vehicle technology, delivering impressive performance and long-range capabilities. With its dual-motor all-wheel drive system, the Model S accelerates from 0 to 60 mph in just 1.99 seconds, redefining speed in the electric vehicle market.",
      "The minimalist interior is equipped with cutting-edge technology, including a massive touchscreen display and advanced autopilot features. The Model S is not just a car; it's an experience that combines sustainability with exhilarating performance.",
    ],
  },
  {
    make: "McLaren",
    model: "720S",
    year: 2023,
    purchasePrice: 300000,
    rentingPrice: 2000,
    engineType: "V8",
    transmission: "Automatic",
    driveType: "RWD",
    horsepower: 710,
    appreciationValue: 5,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947722/download_1_ppxbm0.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947722/McLaren_720s_unb7gw.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947721/download_2_wmvkyb.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947721/McLaren_GT_interior__sntsoy.jpg",
    ],
    description: [
      "The 2023 McLaren 720S is a breathtaking supercar that showcases the brand's commitment to performance and aerodynamics. With its lightweight construction and twin-turbocharged V8 engine, the 720S delivers astonishing acceleration and agility on the track.",
      "The aerodynamic design not only enhances performance but also captivates with its striking aesthetics. Inside, the 720S features a driver-focused cockpit with premium materials and advanced technology, making every drive an exhilarating experience.",
    ],
  },
  {
    make: "Bugatti",
    model: "Chiron",
    year: 2023,
    purchasePrice: 3000000,
    rentingPrice: 10000,
    engineType: "W16",
    transmission: "Automatic",
    driveType: "AWD",
    horsepower: 1500,
    appreciationValue: 10,
    mainImage:
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947058/CHIRON_EDITION_NOIRE_unmjtt.jpg",
    additionalImages: [
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947059/BUGATTI_FAN_CLUB_on_Instagram__Bugatti_Chiron_Sport_Noire_Follow_bugatti_fanclub_supercarsinmanchest___Bugatti_chiron_Super_cars_Sports_car_ihfpw2.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947058/download_3_gbynl5.jpg",
      "https://res.cloudinary.com/duqlw2kta/image/upload/v1729947058/download_2_emlazt.jpg",
    ],
    description: [
      "The Bugatti Chiron 2023 is the pinnacle of automotive engineering, combining unparalleled performance with breathtaking design. Powered by a quad-turbocharged W16 engine, it produces an astounding 1500 horsepower, allowing it to reach speeds that defy belief.",
      "Every aspect of the Chiron is meticulously crafted, from its luxurious interior to its striking exterior. This hypercar is not just about speed; it represents the ultimate in exclusivity and craftsmanship, making it a true icon in the automotive world.",
    ],
  },
];

export default cars;
